### ISSUE TITLE
Shouldn't need NuPIC

### ISSUE THREAD

**Issue by BoltzmannBrain** [numenta/NAB#103]
The readme specifies NuPIC is only needed if running the Numenta detector, yet run.py always runs `from nab.detectors.numenta.numenta_detector import NumentaDetector`, which imports from NuPIC.

**Comment by subutai** [comment]
Is this critical? We can also change the readme :)

**Comment by BoltzmannBrain** [comment]
Not critical, definitely post-beta launch, but it may be better to allow users to run NAB w/o NuPIC. For now we can change the readme, and consider revising the code down the road?

**Comment by subutai** [comment]
Sounds good.
