### ISSUE TITLE
Tune Skyline parameters

### ISSUE THREAD

**Issue by BoltzmannBrain** [numenta/NAB#109]
We may be able to tune Skyline parameters to score better on NAB.

**Comment by subutai** [comment]
@BoltzmannBrain Should @zuhaagha look into this?

**Comment by BoltzmannBrain** [comment]
Yes this would be a good task. Outcomes of this tuning should include the Skyline version number in the scoreboard, and comments in the code about the tuning--currently we just comment out parts of the algorithm, and this is confusing.

**Comment by BoltzmannBrain** [comment]
I've created a [jira](https://jira.numenta.com/browse/RES-231) for this task.

**Comment by zuhaagha** [comment]
Ok I will get started on it.

**Comment by zuhaagha** [comment]
@BoltzmannBrain For skyline parameter tuning, do you think I should experiment with different combinations of skyline algorithms or use all algorithms that the detector is currently using and only tweak the parameters internal to each of the algorithms (such as number of histogram bins or data points threshold for each bin).

**Comment by BoltzmannBrain** [comment]
@zuhaagha I would start by comparing our implementation against the [original Skyline algorithms](https://github.com/etsy/skyline/blob/master/src/analyzer/algorithms.py). Then understand why we have some of them commented out: if we currently run algorithms A, C, D, and F, try adding B back in and analyze the results, and repeat with E. That is, try different combos of the algorithms to understand how they affect the results.

It doesn't look like the algorithms have explicit params anyway, so attempts at tuning would fundamentally change the algorithms, which is not what we want to do when trying to improve detectors' performances on NAB.
