### ISSUE TITLE
Create a CI build for NAB that builds NuPIC and runs NAB

### ISSUE THREAD

**Issue by BoltzmannBrain** [numenta/NAB#117]
NAB, specifically the Numenta detector, can break with changes to NuPIC. A simple detection test needs to be written and added to the NuPIC build.

**Comment by rhyolight** [comment]
Better would be to set up a Travis-CI build for NAB that runs every time NuPIC changes.

**Comment by BoltzmannBrain** [comment]
Okay. I'm unfamiliar with Travis-CI but I'll give it a shot!

**Comment by rhyolight** [comment]
Not sure it will be easy. I tried setting it up for `nupic.research` builds, but they have been failing. @subutai Recent NuPIC changes have broken NAB. I think it should be important to add a NAB travis build that gets triggered from NuPIC changes, but it would probably be best if I did it. Do you think this is important?

**Comment by rhyolight** [comment]
BTW, I am `git bisect`ing NuPIC now to find out which commit broke NAB... Will report my findings here.

**Comment by rhyolight** [comment]
```
e6e2e6c1d182624fab96bea7f5ed1d900ed4dbb8 is the first bad commit
commit e6e2e6c1d182624fab96bea7f5ed1d900ed4dbb8
Author: David Ray <cognitionmission@gmail.com>
Date:   Mon Feb 23 16:18:37 2015 -0600

    Fix for broken test #1831
```

**Comment by rhyolight** [comment]
Working on this, but there seems to be a problem with the latest wheels that were uploaded to S3. I need to deal with that first.

**Comment by rhyolight** [comment]
[![Build Status](https://travis-ci.org/numenta/NAB.svg?branch=master)](https://travis-ci.org/numenta/NAB)
