### ISSUE TITLE
Update tests

### ISSUE THREAD

**Issue by BoltzmannBrain** [numenta/NAB#118]
Because there were many pre-beta changes, the unit and integration tests should be reviewed and updated as necessary.

**Comment by BoltzmannBrain** [comment]
- update [run_tests.sh](https://github.com/numenta/NAB/blob/master/tests/run_tests.sh)
- reorganize [tests](https://github.com/numenta/NAB/tree/master/tests) into unit and integration folders

**Comment by BoltzmannBrain** [comment]
@subutai do we need [tests/run_tests.sh](https://github.com/numenta/NAB/blob/master/tests/run_tests.sh)? The Travis CI build, as of now, calls `py.test tests/` to run all the unit and integration tests.

**Comment by subutai** [comment]
That should be fine. Is there an easy way to run the tests manually?

**Comment by BoltzmannBrain** [comment]
Just run `py.test` from nab/ or nab/tests/.
