### ISSUE TITLE
Bagging the Numenta detector

### ISSUE THREAD

**Issue by BoltzmannBrain** [numenta/NAB#133]
Bagging the Numenta detector may improve results.

**Comment by subutai** [comment]
@BoltzmannBrain Can you be a bit more specific - what do you mean by "bagging the Numenta detector"? Do you mean using an ensemble of multiple models?

**Comment by BoltzmannBrain** [comment]
Yes, an ensemble of HTM models, as you did [here](https://github.com/subutai/nupic.subutai/tree/master/ensembles). The NAB scoreboard could reflect both the standard Numenta detector and an ensemble method.
