### ISSUE TITLE
Investigate Twitter's Anomaly Detector

### ISSUE THREAD

**Issue by BoltzmannBrain** [numenta/NAB#134]
We should investigate and understand the [Twitter algorithm](https://github.com/twitter/AnomalyDetection), and run in NAB. There's also data in their repo we may consider adding to the the NAB corpus.

Note: the relevant milestone is "During Beta" b/c we should expect the Twitter algorithm to be brought up at future conferences when discussing NAB.

**Comment by tomsilver** [comment]
@BoltzmannBrain this blog post has a pretty good explanation, and some python: https://warrenmar.wordpress.com/tag/seasonal-hybrid-esd/

We could directly use their R code using http://rpy.sourceforge.net/, which has worked well for me in the past, or we could port it to Python, perhaps using the blog post as a starting point. I would be happy to get started on either one

cc @subutai

**Comment by BoltzmannBrain** [comment]
I updated the milestone to ICMLA paper because we would like to include the Twitter algorithm in our results.

@scottpurdy please see @tomsilver's comment above.

**Comment by subutai** [comment]
It is fine to use their R code for now. We just need to reformat the output so it can be input to NAB. NAB was designed with this in mind and there is a specification for that.

**Comment by scottpurdy** [comment]
Yes, this will be a good validation that it is easy to get externally-generated results into the appropriate format for NAB.

**Comment by BoltzmannBrain** [comment]
It would also be great to document the process of running the NAB data w/ an external algorithm (i.e. Twitter in R) and following both [NAB entry point paths 1 and 2](https://drive.google.com/a/numenta.com/file/d/0B1_XUjaAXeV3NmxhbEFtZVZ4TmM/view). This would be a helpful example to post to the repo.

**Comment by tomsilver** [comment]
@BoltzmannBrain shall I give that a try?

@scottpurdy

**Comment by BoltzmannBrain** [comment]
@tomsilver is taking this on, and documenting [here](https://github.com/numenta/NAB/wiki/Twitter%20Anomaly%20Detector). For now we'll include the algorithm detections (NAB entry path 3), and later we can add the algorithm (NAB entry path 1) if we choose.

**Comment by BoltzmannBrain** [comment]
@tomsilver we should run the two Twitter algorithm variations independently. If files cannot run for a given alg, they should be scored 0.

**Comment by BoltzmannBrain** [comment]
Closing, with followup in #160.
