### ISSUE TITLE
FAQ page

### ISSUE THREAD

**Issue by BoltzmannBrain** [numenta/NAB#137]
The wiki should include a FAQ page. A good place to start is the ["Nupic or NAB for Apnea Data"](http://lists.numenta.org/pipermail/nupic_lists.numenta.org/2015-April/date.html#10815) mailing list conversation, particularly [this post](http://lists.numenta.org/pipermail/nupic_lists.numenta.org/2015-April/010834.html).

**Comment by BoltzmannBrain** [comment]
I've started a note sheet to collect FAQs [here](https://www.evernote.com/l/AN1e176exl9PwaPnZ3slTEA9iw5WCPWz3Dw).

**Comment by SaganBolliger** [comment]
Copied the note sheet into a page at https://github.com/numenta/NAB/wiki/FAQ

**Comment by BoltzmannBrain** [comment]
Okay thanks. Please also suggest additional question-answers to add.
