### ISSUE TITLE
Add NuPIC data

### ISSUE THREAD

**Issue by BoltzmannBrain** [numenta/NAB#138]
_This is a subtask of #132_
Some of the data for [NuPIC examples](https://github.com/numenta/nupic/tree/master/nupic/datafiles/extra) -- namely hotgym -- should be added to NAB.
@subutai do you think we should ask the NuPIC community if they have data to potentially contribute to NAB? It would be great if they have some known-cause data.

**Comment by subutai** [comment]
We could - feel free to do that if you want. The issue with hotgym is that it does not have known anomalies as such. We can visually look at it and label it.

**Comment by BoltzmannBrain** [comment]
Okay, I think I'll consider this again after going through some public datasets. We would have to hand label any data we get anyway, correct?

**Comment by subutai** [comment]
Yes, but it's a qualitative difference whether it has some actual known anomalies in it vs us just looking visually for anomalies.

**Comment by BoltzmannBrain** [comment]
Right, then when asking the community I would stipulate we're looking for data with known anomalies.
