### ISSUE TITLE
Check NuPIC SHA to ensure score matches scoreboard

### ISSUE THREAD

**Issue by scottpurdy** [numenta/NAB#143]
The NuPIC results were computed on March 26th.

1. Find the SHA for the version of NuPIC on March 26th
2. Build that version of NuPIC (making sure to use the associated nupic.core version)
3. Run NAB against that version of NuPIC to ensure the score matches what we have recorded
4. Update the wiki with the SHA, assuming the scores match

Put versions for NAB, NuPIC, and Skyline on the scoreboard:
https://github.com/numenta/NAB/wiki/NAB-Scoreboard

**Comment by scottpurdy** [comment]
@subutai @BoltzmannBrain - Is this right?

@tomsilver

**Comment by subutai** [comment]
Looks good. We need to also run with the March 26 version of NAB and include the NAB SHA in the wiki.

**Comment by tomsilver** [comment]
After running the NAB version from March 26 with the respective nupic and nupic.core, I got the following scores:

Final score for 'numenta_reward low FN rate' = 77.25
Final score for 'numenta_reward low FP rate' = 66.90
Final score for 'numenta_standard' = 72.69

Which is consistent with what was reported on the scoreboard. Next we will track down the change between March 26 and present that caused the drop in scores. @scottpurdy and I will discuss.

**Comment by tomsilver** [comment]
I believe I have tracked down the discrepancy to this nupic commit from April 21 (https://github.com/numenta/nupic/commit/52eec32922fbd1f8a2041b584b09eabe1d8bfe84) in which @scottpurdy added the Anomaly region. 

@scottpurdy @BoltzmannBrain @subutai any thoughts on why this change might have led to a decrease in the final NAB scores?

After reverting nupic to this commit (and nupic.core and NAB respectively), I got

Final score for 'numenta_reward low FN rate' = 65.99
Final score for 'numenta_reward low FP rate' = 59.26
Final score for 'numenta_standard' = 60.35

**Comment by tomsilver** [comment]
Actually I may have spoken too soon - the change might have been a previous commit. Will follow up when I confirm.

**Comment by scottpurdy** [comment]
Yeah that commit wouldn't have affected anything using the CLAModel

**Comment by tomsilver** [comment]
Update on this: we tracked down the issue to a change on March 30th in which numpy.random was swapped out for NupicRandom in the RandomDistributedScalarEncoder. Further tests revealed that the final score is highly sensitive to the seed of the random number generator. Increasing w from 21 to 31 led to significantly lower variation, but a decrease in final scores. It should be possible to tune the other parameters (such as increment and decrement) to achieve higher final scores with lower variation. @BoltzmannBrain  I recommend closing this issue and opening a new one for tuning parameters at w=31 (feel free to assign it to me).

**Comment by BoltzmannBrain** [comment]
@subutai this is no longer an issue, correct? Now we're using the current version of NuPIC, checking the scores w/ the regression tests.

**Comment by subutai** [comment]
Correct. Closing.
