### ISSUE TITLE
Script to add detectors to thresholds file

### ISSUE THREAD

**Issue by BoltzmannBrain** [numenta/NAB#145]
@tomsilver we need an easy way for users to add their custom detector's name(s) into the [thresholds file](https://github.com/numenta/NAB/blob/master/config/thresholds.json). The scoring step needs the detector name to be a key.

**Comment by tomsilver** [comment]
@BoltzmannBrain How about a function in scripts/ that takes the name of the new detector (e.g. "twitter") and sets up the thresholds file, and also adds a directory with the detector's name in the results/ directory, populated with the category directories?

I think those were all the things I had to do manually.

**Comment by BoltzmannBrain** [comment]
@tomsilver good idea! Please include unit testing for this.

**Comment by BoltzmannBrain** [comment]
Closed with #148
