### ISSUE TITLE
Clean the scripts directory

### ISSUE THREAD

**Issue by BoltzmannBrain** [numenta/NAB#146]
The scripts in the scripts directory are from an old version of NAB. Do we still need them? Do they work?

**Comment by BoltzmannBrain** [comment]
@tomsilver please take a look

**Comment by tomsilver** [comment]
@BoltzmannBrain the scripts seem to still work and they may be useful for adding new data or new detectors to NAB. I would recommend revisiting this issue after going through the process of adding new data (e.g. https://github.com/numenta/NAB/issues/144) and also adding a new detector by following Path 1 or 2.

**Comment by subutai** [comment]
I think this has been mostly handled. Closing for now - any further work on this should have specific issues describing specific things to be fixed.
