### ISSUE TITLE
Add Twitter algorithms

### ISSUE THREAD

**Issue by BoltzmannBrain** [numenta/NAB#160]
Port the R code to Python and add to NAB detectors.

**Comment by subutai** [comment]
Do we need to port it? That could be a lot of work with minimal benefits. Can we leave it as R code? It is a nice example of how you can take an external algorithm and get it working with NAB.

**Comment by BoltzmannBrain** [comment]
I agree; was adding this issue because I thought it was our original plan. I think it's great as is with the documentation in the wiki.
