### ISSUE TITLE
Raise minimum file length to 4000

### ISSUE THREAD

**Issue by BoltzmannBrain** [numenta/NAB#164]
When we add more data we'll raise the min file size requirement, and need to then remove the following files b/c they're <2000 data instances each:
- the 12 "Ad Exchange" data files
- "mole_key_hold"
- "realAWSCloudwatch/iio_us-east-1_i-a2eb1cd9_NetworkIn.csv"

This is related to #132

**Comment by subutai** [comment]
@BoltzmannBrain Is this issue obsolete now?

**Comment by BoltzmannBrain** [comment]
We should decide. Initially this issue was created when there were only a couple files w/ < 2000 records, but now we have more more data files in this group. It would be nice to have a minimum file length for NAB, but this would mean removing nine data files from the v1.0 dataset.

**Comment by subutai** [comment]
Well, we can't make changes to this now so this would have to be an issue for v2.0.  I think if we end up with more than 100 files we can start considering removing some.  Until then it is more valuable to have the real data even if it is imperfect.  Closing the issue for now.
