### ISSUE TITLE
Newbie installation problems

### ISSUE THREAD

**Issue by breznak** [numenta/NAB#17]
Trying to run NAB, I ran into a problem: 

nupic_py27mmm@mmm-U2442:~/nupic/NAB$ python run.py 
{'dataDir': 'data',
 'detect': False,
 'detectors': ['numenta'],
 'labelDir': 'labels',
 'numCPUs': None,
 'optimize': False,
 'probationaryPercent': 0.15,
 'profilesPath': 'config/user_profiles.yaml',
 'resultsDir': 'results',
 'score': False,
 'thresholdPath': 'config/threshold_config.yaml'}
Proceed? (y/n): y
/home/mmm/nupic/env_py27/local/lib/python2.7/site-packages/pandas/core/frame.py:1771: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "DataFrame index.", UserWarning)
Traceback (most recent call last):
  File "run.py", line 152, in <module>
    main(args)
  File "run.py", line 65, in main
    runner.initialize()
  File "/home/mmm/nupic/NAB/nab/runner.py", line 90, in initialize
    self.corpusLabel.initialize()
  File "/home/mmm/nupic/NAB/nab/labeler.py", line 124, in initialize
    self.getLabels()
  File "/home/mmm/nupic/NAB/nab/labeler.py", line 158, in getLabels
    labels["label"].values[indices] = 1
IndexError: unsupported iterator index

I've tried pulling #15 which mentions some bugfix to labeling, but that gives me another error (so I can't tell w/o a vanilla running)

**Comment by BoltzmannBrain** [comment]
@subutai good to close?

**Comment by subutai** [comment]
Yup!
