### ISSUE TITLE
Replace AnomalyLikelihood class with the new NuPIC version

### ISSUE THREAD

**Issue by BoltzmannBrain** [numenta/NAB#172]
The Numenta detector uses its own implementation of the AnomalyLikelihood class ([here](https://github.com/numenta/NAB/blob/4b56c59e73452e16e487467304fd54c210651d26/nab/detectors/numenta/numenta_detector.py#L108-L166)). We should look into replacing it with the [NuPIC version](https://github.com/numenta/nupic/blob/master/nupic/algorithms/anomaly_likelihood.py#L69), which has improved computation efficiency as of [#2535](https://github.com/numenta/nupic/pull/2535). Before deciding on the change it's important to run NAB to investigate the difference in speed and score.

**Comment by vitaly-krugl** [comment]
@BoltzmannBrain: here are a few additional points

1. There is a follow-up PR https://github.com/numenta/nupic/pull/2544 for nupic's AnomalyLikelihood class that hasn't been merged yet. This PR contains important configuration and stats refresh changes. We're targeting this change for the upcoming nupic 0.2.13 release.
2. NAB's requirements.txt doesn't have a nupic entry, much less a versioned one.
3. As part of the difference in speed investigation, you will probably want to contrast the following
 Existing NAB code and existing version of nupic
 Existing NAB code and new version of nupic (e.g., 0.2.13)
 Updated NAB that uses AnomalyLikelihood class from nupic (0.2.13?)

**Comment by BoltzmannBrain** [comment]
@vitaly-krugl thank you, I'm planning to test NAB with the new NuPIC once it's released and then make the necessary changes (if there are any). I will then tag NAB v0.8.1 with this version of NuPIC.

NuPIC is held out of the requirements.txt because we don't want to require people have it to run their algorithms on NAB. That is, a user could install NAB and run `python run.py -d my_awesome_detector` without having to mess with NuPIC.
