### ISSUE TITLE
Try Yahoo anomaly detection package with NAB

### ISSUE THREAD

**Issue by subutai** [numenta/NAB#176]
Yahoo has open sourced a time series anomaly detection package. We should try it with NAB.  Details here:

https://github.com/yahoo/egads

Paper is here (link on github page is broken):

https://labs.yahoo.com/publications/6773/generic-and-scalable-framework-automated-time-series-anomaly-detection

**Comment by breznak** [comment]
is anyone working on this? I may look at it soon..

**Comment by subutai** [comment]
@breznak We'd love to do this though not sure we'll have the time. It would be great if someone else could do this. Wait until NAB is at 1.0 first though - there are a few NAB repo changes remaining.

**Comment by breznak** [comment]
> Wait until NAB is at 1.0 first though - there are a few NAB repo changes remaining.

Thanks for the info @subutai ! A rough ETA on the NAB 1.0 ? Meanwhile I'll be preparing the models and running tests

**Comment by subutai** [comment]
Very very soon. Latest maybe end of next week??

**Comment by breznak** [comment]
Great, thanks! Just read your answer on mail :)

**Comment by breznak** [comment]
@wattik This could be interesting 4 you.

**Comment by BoltzmannBrain** [comment]
Upgrading to P2 b/c the Yahoo package includes some traditional statistical techniques that we've been asked about (i.e. ARIMA).

@breznak have you looked into this?

**Comment by breznak** [comment]
@BoltzmannBrain @wattik and I should be working on this in about a month...

**Comment by BoltzmannBrain** [comment]
Added to the wiki.
