### ISSUE TITLE
Make plotting script more usable

### ISSUE THREAD

**Issue by BoltzmannBrain** [numenta/NAB#182]
Use command line args, where there could be a param for specifying a data dir (below), or the user could specify a single data file.

```
files = glob.glob("data/realAdExchange/*")
  dataFiles = []
  for f in files: dataFiles.append(f.strip("data/"))

  for i in xrange(len(dataFiles)):
    dataPlotter = PlotNAB(
        dataFile=dataFiles[i],
        dataName="Labels inspection for " + dataFiles[i])
    dataPlotter.plotRawData(
        withLabels=False,
        withWindows=True,
        withProbation=True)
```

**Comment by breznak** [comment]
Guys, would you be interested in using (and mentioning in the plot readme section) the project https://github.com/nupic-community/nupic.visualizations ? 
In regards to this project: 
* `+` it can nicely and interactively work with the raw & results data from NAB experiments. 
* `-` cannot show more graphs at once, as it works here now; but you could likely change it to that behavior. 
* `?+` has plans for really nice features for anomaly highlighting

CC @jefffohl

**Comment by BoltzmannBrain** [comment]
Possibly. How is it different from the current plotting script and the NAB visualizer? Would you be able to generate some example NAB figures? I looked in the nupic.visualizations NAB examples dir but only found the current NAB visualizer.

**Comment by breznak** [comment]
@BoltzmannBrain the NAB visualizer there is outdated, the generic tool can open the files now. The example figure can be seen on the project page, or you can just clone and run to test interactively.
