### ISSUE TITLE
Add NAB to NuPIC regression tests

### ISSUE THREAD

**Issue by subutai** [numenta/NAB#192]
NuPIC regression tests should fail if performance on NAB drops below published results, or becomes higher than published results (we need to know either way!). These tests can skip the optimize step and use the currently checked in best thresholds.

Code for regression tests are here:

https://github.com/numenta/nupic.regression

Depends on:

https://github.com/numenta/nupic/issues/2606

**Comment by rhyolight** [comment]
Is this work scheduled to be done by someone? Do you have any expectations from me?

**Comment by subutai** [comment]
@rhyolight Yes. We might come to you with questions in a bit.

**Comment by BoltzmannBrain** [comment]
https://github.com/numenta/nupic.regression/pull/25
https://github.com/numenta/nupic.regression/pull/26
https://github.com/numenta/nupic.regression/pull/27
