### ISSUE TITLE
Visualizations: order the pictures by dataset

### ISSUE THREAD

**Issue by breznak** [numenta/NAB#209]
currently the results are ordered by method, then example, eg. `numenta/Twitter/XXX` That results in ordering of images in the `http plot`; 

It would be easier for comparisons if the data is sorted by example, and then by method (random, numenta,...). 

Or even add a checkbox which methods to include in the plot. And even better, if they (methods) could be in 1 image.

**Comment by subutai** [comment]
Not sure what you want to do. What reports or what piece of code do you want to modify? Closing (you can re-open with a tighter definition).
