### ISSUE TITLE
Inlude state-of-the art results (even offline)

### ISSUE THREAD

**Issue by breznak** [numenta/NAB#213]
Allow to add `only results` for certain algorithms, without need to run the alg. Eg if the alg. does not meet NAB's requirements to be included (speed, online,..) or is not publicly available, we should include the state of the art results for given dataset. 

This way it's very easy to add results data for comparison. (Can be used even to compare diff. Nupic versions)

Implementation: 
is quite simple, just have a folder with `3rdparty_results` with CSVs and just copy the files to results before evaluation/plotting. Of course the results will be only available for a subset of tests, but that should not matter.

**Comment by subutai** [comment]
I'm not sure what is intended by this issue. We do not plan to include results for algorithms that do not meet the NAB criteria for streaming algorithms. We are fine listing results on the scoreboard for any and all algorithms that can run on the NAB benchmark as it is designed.  

Note that this is an open source repository. Anyone can download/fork it and free to use it in other ways.

Closing the issue for now.
