### ISSUE TITLE
Include Adaptive Resonance Theory (ART) algorithm 

### ISSUE THREAD

**Issue by breznak** [numenta/NAB#214]
ART, https://en.wikipedia.org/wiki/Adaptive_resonance_theory 
can be used for anomaly detection, even should fit NAB requirements, we should include it into our battery of anomaly classifiers for benchmarking!

https://github.com/nupic-community/nupic.audio/issues/18
PS: huh, I'm creating so much issues it crashed Github for a while :see_no_evil:

**Comment by subutai** [comment]
Is there an open source code base for easily running ART? Note that we have to run it in a way that fulfills the requirements for NAB algorithms.

**Comment by BoltzmannBrain** [comment]
@breznak maybe enter this algorithm into the [NAB competition](http://numenta.org/nab/)?
