### ISSUE TITLE
New anomaly detection algorithms

### ISSUE THREAD

**Issue by breznak** [numenta/NAB#215]
Adding new labelers, algorithms to NAB. 
This is a super issue for: 

- [ ] [Yahoo anomaly detector](https://github.com/numenta/NAB/issues/131)
- [ ] [Adaptive Resonance Theory](https://github.com/numenta/NAB/issues/214)
- Implement/get results from Papers on online anomaly detection
 - [ ] http://bourbon.usc.edu/iml/projects/nsf-dc-0917340/anomaly.pdf
 - [ ] http://www.hpl.hp.com/techreports/2011/HPL-2011-8.pdf
 - [ ] and much more.. 

See https://github.com/numenta/NAB/issues/213 for alternative results.

**Comment by BoltzmannBrain** [comment]
Closing this super issue b/c we would prefer tracking add'l algorithms under a milestone.
