### ISSUE TITLE
consider anomaly start times different from anomaly detected times

### ISSUE THREAD

**Issue by welch** [numenta/NAB#228]
NAB is a terrific resource, and I am enjoying benchmarking with it. Thank you for assembling and publishing this framework.

The insistence that an anomaly be detected in real time (anomaly start time == anomaly detected time) is not quite realistic in a production setting.  A benchmark in which the detector outputs a retrospective anomaly start time within a specified lag from realtime would be a welcome variation. In a real setting, such a retrospective start time is useful when seeking out correlated items and events once an alarm has been raised. 

(Also, I noticed in your instructions for human anomaly annotation that the advice to not look ahead while scoring came at the very end of the list, and was not much emphasized. You might suggest they actually cover up the future part of the series while scoring, so that their anomaly start times == their anomaly detect times.)

**Comment by subutai** [comment]
@welch Thanks for the feedback!  Good point about the labeling writeup. We should do a scrub of some of that stuff as it was written a while ago.

Regarding lags, that is handled within anomaly windows. There's no concrete anomaly start time, instead there is a window within which to detect the anomaly. So if a detector is a little bit late in detecting anomalies, that's ok, as long as the detection is within the window. However a detector that does not require much of a lag will be scored a little higher.  Do you think we need to handle lags beyond the anomaly window?

**Comment by welch** [comment]
It would be interesting/realistic if the unpenalized lag was an actual parameter. This is probably unwelcome complexity in a benchmarking setting though.

Rethinking my remark about the labelling: some sets have ground truth labels that did not come from human labelers, making lookahead irrelevant. Perhaps it is more consistent to bless your labelers' use of the entire series, since the benchmark is not about reproducing human labelling behavior.
