### ISSUE TITLE
Mention/replace new plot tool in readme

### ISSUE THREAD

**Issue by breznak** [numenta/NAB#233]
Guys, 

would you be interested in using (and linking from your readme) our tool https://github.com/nupic-community/nupic.visualizations ? 

The functionality is getting more mature and we'd like to attract more users from different use-cases. 
Currently the tool does NOT support plotting multiple files at once, but for a single (OPF) file it imho offers better functionality than the plot.ly/python solution: anomaly highlighting, interactive graph browsing, possible online updates/monitoring, ... It can be run without hassle from web as well. 

Or feedback how it feels for your use-case would be awesome :wink: 

ref: https://github.com/nupic-community/nupic.visualizations/issues/22

Thanks,

**Comment by BoltzmannBrain** [comment]
@breznak good work on this. It appears to have the same functionality as the [NAB data visualizer](https://github.com/numenta/NAB/tree/master/scripts#alternative-data-and-results-visualization), although   not being able to plot multiple files at once is a drawback. I would consider replacing the current visualizer with the nupic.visualization tool if the following functionality is added:
- Plot multiple files at the same time.
- Plot by keyword; e.g. I can search the NAB visualizer for "Twitter" and get all the Twitter data plots.

I don't see the nupic.visualization tool as a replacement for the plotly tool in NAB, which offers much more plotting features.
