### ISSUE TITLE
NAB Dockerfile

### ISSUE THREAD

**Issue by alirezahajibagheri** [numenta/NAB#239]
Hello everyone,

I was trying to test an anomaly detection algorithm and that's when I came across NAB. I tried different methods to install NAB on my Linux machine and had no luck to get rid of several issues related to NuPIC  (can not find math.h and stuff like that) so I ended up using their docker file and thought it would be nice to have one for NAB itself to get it up and running as fast as possible. I am not sure if this is the write place to post it but I thought it might be useful for others. I have upload the docker file on GitHub.Gist and here is a link to it:

https://gist.github.com/alirezahajibagheri/ba49061055588456e0ea8e53677f3a93

Hope this is useful. 

Cheers

**Comment by subutai** [comment]
@alirezahajibagheri That's great - thank you!  It could be really useful to others. I suggest the best place to post it is on the HTM Forum, in the NuPIC category: https://discourse.numenta.org

I am closing the issue as it is not really a bug or change request, but you did get our attention 😄 Please post it to the list!

**Comment by subutai** [comment]
@rhyolight Perhaps worth having a NAB sub-category under NuPIC?

**Comment by oxtopus** [comment]
I created https://github.com/nupic-community/NAB-Dockerfile (currently empty) for this.

**Comment by BoltzmannBrain** [comment]
Thanks @alirezahajibagheri, running NAB via Docker will be a great addition!

@lscheinkman if I recall correctly, didn't you also use Docker for NAB? If so, are there differences between this dockerfile and yours?
