### ISSUE TITLE
Optimizer does not work optimally

### ISSUE THREAD

**Issue by smirmik** [numenta/NAB#244]
I have a dataset with very low optimal thresholds (lower than 0.1) , and if i to start optimizer he end his work on 0.5 with best score -118. But if i change initialGuess in optimizer.py to 0.0 and start again, i get parameter 0.1 with -93 best score.

**Comment by BoltzmannBrain** [comment]
Could you please clarify your issue, with the code and data you're running?

**Comment by Smirmik** [comment]
Unfortunately I can not find exactly the dataset of which i wrote the above, but there is another example;

~/numenta/NAB/nab/optimizer.py
43   initialGuess=0.5

m-smirnov@ubuntu14:~/numenta/NAB$ python run.py -d CADV0DT01DW1NB008MC008OC008 --optimize
m-smirnov@ubuntu14:~/numenta/NAB$ python run.py -d CADV0DT01DW1NB008MC008OC008 --score --normalize

Final score for 'CADV0DT01DW1NB008MC008OC008' detector on 'reward_low_FP_rate' profile = -0.87

Final score for 'CADV0DT01DW1NB008MC008OC008' detector on 'reward_low_FN_rate' profile = 9.68

Final score for 'CADV0DT01DW1NB008MC008OC008' detector on 'standard' profile = 6.76


~/numenta/NAB/nab/optimizer.py
43   initialGuess=0.0

m-smirnov@ubuntu14:~/numenta/NAB$ python run.py -d CADV0DT01DW1NB008MC008OC008 --optimize
m-smirnov@ubuntu14:~/numenta/NAB$ python run.py -d CADV0DT01DW1NB008MC008OC008 --score --normalize

Final score for 'CADV0DT01DW1NB008MC008OC008' detector on 'reward_low_FP_rate' profile = 0.70

Final score for 'CADV0DT01DW1NB008MC008OC008' detector on 'reward_low_FN_rate' profile = 9.68

Final score for 'CADV0DT01DW1NB008MC008OC008' detector on 'standard' profile = 6.76

Note the difference in the results.
This means that the results of your algorithm may be calculated more accurately (possibly been underestimated)

**Comment by Smirmik** [comment]
https://drive.google.com/open?id=0BxbPAYsdde57WEtXVGxuUDYyWWs

**Comment by BoltzmannBrain** [comment]
We have unit tests to explicitly test for different initial guesses ([here](https://github.com/numenta/NAB/blob/master/tests/unit/optimizer_test.py#L104)). Do you have any differences from NAB master?

**Comment by Smirmik** [comment]
These tests are based on smooth curves, but in reality it turns out very discrete function with long straight sections, with one value. Imagine chart as an inverted truncated cone: \ __ / is necessary for the middle value of 0.5, and the peaks are closer to 0.0 and 1.0 - in this case, your maximum search algorithm does not work.

I would like to write an additional test, but try to end my algorithm to the deadline of the NAB Competition.
Now I have the following results:

    "CADV5DT00DW1NB008MC008OC0": {
        "reward_low_FN_rate": 55.630421448448274,
        "reward_low_FP_rate": 38.76855047883621,
        "standard": 48.397115378267245
    },

    "CAD170201V022DT00DW1NB06MC16OC00": {
        "reward_low_FN_rate": 50.59150643841954,
        "reward_low_FP_rate": 47.660689733219826,
        "standard": 48.73208724383621
    },

What do you think, is there any chance of winning?

**Comment by BoltzmannBrain** [comment]
@Smirmik yes there's a chance 😉 please submit your algorithm to nab@numenta.org according to the [details on the competition page](http://numenta.org/nab/#algorithms-category). The earlier you submit the better b/c then we have time to sort out any issues with the submission. I'll dig a little more into the optimizer this weekend, thank you for pointing out this issue.

**Comment by breznak** [comment]
There hasn't been any progress on this issue. 

@smirmik Can you release the dataset as CreativeCommons license

> https://drive.google.com/open?id=0BxbPAYsdde57WEtXVGxuUDYyWWs

and submit it as a dataset here, or to community NAB https://github.com/htm-community/NAB  ? 

Then we can repreduce the issue with "optimizer not finding best results"

**Comment by smirmik** [comment]
> There hasn't been any progress on this issue.
> 
> @smirmik Can you release the dataset as CreativeCommons license
> 
> > https://drive.google.com/open?id=0BxbPAYsdde57WEtXVGxuUDYyWWs
> 
> and submit it as a dataset here, or to community NAB https://github.com/htm-community/NAB ?
> 
> Then we can repreduce the issue with "optimizer not finding best results"

@scottpurdy solved this problem in #257.   But it was not included in the main branch.
