### ISSUE TITLE
NAB scoring requires NuPIC installed, contrary to README

### ISSUE THREAD

**Issue by floybix** [numenta/NAB#250]
Hi,

The README says to install _"NuPIC (only required if running the Numenta detector)",_ but:

```
$ python run.py -d null --optimize --score --normalize
Traceback (most recent call last):
  File "run.py", line 179, in <module>
    from nab.detectors.gaussian.windowedGaussian_detector import WindowedGaussianDetector
  File "/Users/felix/Devel/NAB/nab/detectors/gaussian/windowedGaussian_detector.py", line 23, in <module>
    from nupic.algorithms import anomaly_likelihood
ImportError: No module named nupic.algorithms
```

**Comment by BoltzmannBrain** [comment]
Good catch, thank you! I'll followup with a PR shortly.

**Comment by BoltzmannBrain** [comment]
Importing the [`normalProbability()`](https://github.com/numenta/nupic/blob/master/src/nupic/algorithms/anomaly_likelihood.py#L621) method is problematic. We should instead calculate the tail probabilities directly.
