### ISSUE TITLE
Relative position computation is confusing

### ISSUE THREAD

**Issue by scottpurdy** [numenta/NAB#258]
Right now there are some confusing aspects of how the relative position is computed:
- Rows inside the window have their position divided by `scaledSigmoid(-1.0)` while rows after the window do not.
- The relative position is computed by dividing some index offset by the size of the window. But for rows after the window, the divisor is one less than the window size.
- The last row in the window is given an offset of `-1` (divided by the window size) while the next row is given an offset of `+1` (divided by one less than the window size) which adds a confusing asymmetry.

I propose that we:
- Give an offset of `0` divided by one less than the window size for the last row in the window.
- Divide the relative position by `scaledSigmoid(-1.0)` for rows after the window as well as inside the window.

This would mean the relative position can be calculated with the same formula for rows inside and after a window. It would more clearly line up with the documentation describing the window. I don't expect the NAB scores to change very much, this is more for clarity of the method and the code.

CC @BoltzmannBrain @subutai

**Comment by BoltzmannBrain** [comment]
Thanks for bringing this up @scottpurdy 

> Rows inside the window have their position divided by scaledSigmoid(-1.0) while rows after the window do not.

This points out an inconsistency with the current paper. In the code the front of a window is a relative position of -1.0, but in the paper (Fig. 3) this is shown as -3.0. Both are correct though. In the code, a relative position of -1.0 yields a TP score of 1.0 b/c we divide by scaledSigmoid(-1.0). Going by the paper's equations, a relative position of -3.0 yields a TP score of 1.0.

> I propose that we:...
> Divide the relative position by scaledSigmoid(-1.0) for rows after the window as well as inside the window.

:+1: This would impose a [-1,1] bound on the relative positions, which is more intuitive than [-3,3] and [-1,3].

**Comment by subutai** [comment]
This is fine but note that we cannot make any changes to the scoring algorithm or code for 1.0. This would have to be a post 1.0 change.

**Comment by scottpurdy** [comment]
@subutai totally agree and this shouldn't have any practical impact on scores so it isn't critical to make these changes right away
