### ISSUE TITLE
NuPIC detectors should use the Network API, not the OPF

### ISSUE THREAD

**Issue by rhyolight** [numenta/NAB#275]
Both of Numenta's NuPIC detectors use the OPF as NuPIC's interface. 

```
nab/detectors/numenta/numenta_detector.py
24:from nupic.frameworks.opf.common_models.cluster_params import (
26:from nupic.frameworks.opf.modelfactory import ModelFactory

nab/detectors/numenta/numentaTM_detector.py
26:from nupic.frameworks.opf.common_models.cluster_params import (
28:from nupic.frameworks.opf.modelfactory import ModelFactory
```

They [should use the Network API instead](https://github.com/numenta/nupic/issues/3357#issuecomment-249284934), because it is better suited for anomaly detection problems.

**Comment by rhyolight** [comment]
I changed my mind about this. I think we just need to better document what the OPF is and how it can be used.

**Comment by subutai** [comment]
@rhyolight Yes, I agree. I don't see why it shouldn't use the OPF.  Anomaly models could be a particular model type in the OPF.

**Comment by cogmission** [comment]
@subutai @rhyolight It should be fixed so that you can use Anomaly models without having to declare a predicted field. Right now it throws an exception if you don't specify a ```predictedField``` 
;-)

**Comment by BoltzmannBrain** [comment]
@cogmission the `predictedField` tells the model what value to infer on, which is necessary for any TM model, regardless of the application -- prediction, classification, anomaly detection.

**Comment by cogmission** [comment]
@BoltzmannBrain 
>  the predictedField tells the model what value to infer on

As far as I have seen, the only practical use for "knowing" this field is to state which field a classifier is specified for. This isn't necessary for Anomaly Detection.

**Comment by subutai** [comment]
@cogmission is correct. There is no particular need for predicted field for anomaly detection. It is required only because of a hacky CLAModel.py implementation which should be cleaned up.

**Comment by BoltzmannBrain** [comment]
@cogmission my mistake

**Comment by cogmission** [comment]
@BoltzmannBrain Hey nobody's making mistakes. I regard us as a think tank where even the craziest statements can inspire other thoughts which are inspired. This was the atmosphere of my first job "FizzyLab", and that attitude has stuck with me. I guess that's why I'm very "free" with my utterances. I think its stifling to be in an atmosphere where you have too much to protect and you have to always try to be "right". It's exhausting and in the long run, is detrimental to creativity.
