### ISSUE TITLE
anomaly label + window mismatch

### ISSUE THREAD

**Issue by dmargala** [numenta/NAB#300]
Hi, while looking through the labeled anomalies in the `labels/combined_label.json` and `labels/combined_windows.json` files, I encountered two potential issues:

1) It looks like the first anomaly at in the `realAWSCloudwatch/iio_us-east-1_i-a2eb1cd9_NetworkIn.csv` dataset appears about an hour before the corresponding window. See:

https://github.com/numenta/NAB/blob/master/labels/combined_labels.json#L77
https://github.com/numenta/NAB/blob/master/labels/combined_windows.json#L166

2) Most of the windows seem to be centered on the corresponding anomaly, except for the first anomaly in the `realTraffic/TravelTime_387.csv` dataset. See:

https://github.com/numenta/NAB/blob/master/labels/combined_labels.json#L149
https://github.com/numenta/NAB/blob/master/labels/combined_windows.json#L354

**Comment by minkyung-kim17** [comment]
There is still mismatch in the data. (`realAWSCloudwatch/iio_us-east-1_i-a2eb1cd9_NetworkIn.csv`)
![image](https://user-images.githubusercontent.com/29730975/52693246-817de200-2fa9-11e9-8ba3-de55c96aa77d.png)

Also, there is one window with two anomaly. (`Twitter_volume_CVS.csv`)
In this case, how measure anomaly detector performance? 
![image](https://user-images.githubusercontent.com/29730975/52693286-a83c1880-2fa9-11e9-87e9-704a73f7eb46.png)

**Comment by subutai** [comment]
> There is still mismatch in the data. (`realAWSCloudwatch/iio_us-east-1_i-a2eb1cd9_NetworkIn.csv`)

Hmm, good point. That looks like a bug in the window creation code.  Not sure why that happened.

> Also, there is one window with two anomaly. (`Twitter_volume_CVS.csv`)
> In this case, how measure anomaly detector performance?

This is surprisingly common in streaming data. In these cases we treat this as one anomaly. Earlier detections get preference.
