### ISSUE TITLE
scores.csv file needs to have a bit more information

### ISSUE THREAD

**Issue by subutai** [numenta/NAB#31]
After running NAB you get a _scores.csv file with some useful information. This file should contain most (if not all) the information needed to manually calculate the score. For example, the fn column contains the total number of records. Instead it should contain the number of anomaly windows that were unlabeled because that is what the score is based on.

**Comment by BoltzmannBrain** [comment]
The individual results files -- e.g. 'results/numenta/artificialNoAnomaly/numenta_art_noisy.csv' -- should have the scoring function output for each step in time (i.e. each row). Then we can check the scoring function works as intended.

**Comment by BoltzmannBrain** [comment]
Also included in PR#56, relevant to this issue, is a row at the bottom of the detector results file for totals -- i.e. totaling the results for all datasets.
