### ISSUE TITLE
confusing readme

### ISSUE THREAD

**Issue by fazlekarim** [numenta/NAB#313]
I want to know the labels of each data point. How will I do so?

**Comment by subutai** [comment]
The labels are in the `labels` subdirectory. 

The exact format and details are documented in the NAB Whitepaper, referenced in the main README and here:
 
https://github.com/numenta/NAB/wiki#nab-whitepaper
 
Note that the “label” timestamps are converted to anomaly windows, which are more appropriate for real time temporal data streams and are used for the actual scoring.
