### ISSUE TITLE
 ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by benbastaki** [numenta/NAB#314]
I am trying to validate a dataset (includes time, anomaly_S, likelihood and log +lable),
but I get error below:

  **File "C:\combine_dataset\Framework_V4\NAB\NAB\NAB\score_dataset.py", line 78, in score
    normalized_score = 100 * ( (raw_score - null_score) / (perfect_score - null_score))
ZeroDivisionError: float division by zero**

To pass this error, I edited and add **+0.0000001**  to:
  normalized_score = 100 * ( (raw_score - null_score) / ( (perfect_score - null_score)**+0.0000001** )
but it then, outputs 0 for the score.
raw_score  = -9.0
null_score = -1.0
perfect_score = -1.0

out put:
The best threshold found is: 0.7825
0.0 <<<<<-----------this is 0 but I have anomaly in label.

any suggestion or fix please?

**Comment by lscheinkman** [comment]
@benbastaki The file `score_dataset.py` is not part of NAB. It looks like a custom script
Can you replicate this problem with the released version of NAB?

CC: @rhyolight

**Comment by rhyolight** [comment]
Closing due to lack of response.
