### ISSUE TITLE
can't run htmjava

### ISSUE THREAD

**Issue by yusong0926** [numenta/NAB#315]
(NAB-env) Songs-MacBook-Pro:NAB syu$ python run.py -d htmjava --detect --score --normalize
{'dataDir': 'data',
 'detect': True,
 'detectors': ['htmjava'],
 'normalize': True,
 'numCPUs': None,
 'optimize': False,
 'profilesFile': 'config/profiles.json',
 'resultsDir': 'results',
 'score': True,
 'skipConfirmation': False,
 'thresholdsFile': 'config/thresholds.json',
 'windowsFile': 'labels/combined_windows.json'}
Proceed? (y/n): y
/Users/syu/sonar4/algorithms/NAB/nab/labeler.py:132: FutureWarning: pandas.tslib is deprecated and will be removed in a future version.
You can access Timestamp as pandas.Timestamp
  f = data["timestamp"][data["timestamp"] == pandas.tslib.Timestamp(t)]

Running detection step
0: Beginning detection with htmjava for realTraffic/speed_6005.csv
2: Beginning detection with htmjava for realTweets/Twitter_volume_UPS.csv
4: Beginning detection with htmjava for artificialWithAnomaly/art_daily_nojump.csv
6: Beginning detection with htmjava for artificialNoAnomaly/art_daily_perfect_square_wave.csv
8: Beginning detection with htmjava for realTraffic/speed_7578.csv
10: Beginning detection with htmjava for realTweets/Twitter_volume_CRM.csv
12: Beginning detection with htmjava for realAdExchange/exchange-2_cpc_results.csv
14: Beginning detection with htmjava for realAdExchange/exchange-4_cpm_results.csv
........ 16: Beginning detection with htmjava for realAWSCloudwatch/elb_request_count_8c0756.csv
Traceback (most recent call last):
  File "run.py", line 210, in <module>
    main(args)
  File "run.py", line 69, in main
    runner.detect(detectorConstructors)
  File "/Users/syu/sonar4/algorithms/NAB/nab/runner.py", line 134, in detect
    self.pool.map_async(detectDataSet, args).get(99999999)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
TypeError: slice indices must be integers or None or have an __index__ method
(NAB-env) Songs-MacBook-Pro:NAB syu$

**Comment by rhyolight** [comment]
What version of java are you running?

`java -version`

**Comment by rhyolight** [comment]
Interesting, I got the same error when I ran. I'll have to defer to @cogmission about this. 

    python run.py -d htmjava --detect --score --normalize

```
........ 16: Beginning detection with htmjava for realAWSCloudwatch/elb_request_count_8c0756.csv
claLearningPeriod is deprecated, use learningPeriod instead.
Traceback (most recent call last):
  File "run.py", line 210, in <module>
    main(args)
  File "run.py", line 69, in main
    runner.detect(detectorConstructors)
  File "/Users/mtaylor/nta/NAB/nab/runner.py", line 134, in detect
    self.pool.map_async(detectDataSet, args).get(99999999)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
TypeError: slice indices must be integers or None or have an __index__ method
```

**Comment by yusong0926** [comment]
thanks.

**Comment by suhasDataken** [comment]
I uninstalled numpy1.12.0, then installed numpy 1.11.1 and got past this issue.

**Comment by rhyolight** [comment]
@yusong0926 Does the numpy version update above fix this issue for you?

**Comment by cogmission** [comment]
@rhyolight - Wow! Sorry, I didn't even see some of these issues... 

@yusong0926 - I hope this solves your issue? (and thanks @suhasDataken!)
