### ISSUE TITLE
Spatial Tolerance

### ISSUE THREAD

**Issue by SimonWesterlindVPD** [numenta/NAB#317]
Hello Numenta!

For the HTMjava algorithm you have included a Spatial Tolerance which thereafter is used as an anomaly detection directly applied to the data. This is a reasonable addition to the HTM's anomaly likelihood to detect spatial anomalies in practice. However, given that this is an addition to the HTM which could be applied to all other algorithms also (but it has not been applied to assist the other algorithms), does this not make for an unfair comparison of the algorithms and a boost to the performance of the HTM, which is not based on HTM technology? Pardon me if I got something wrong!

Cheers!

**Comment by subutai** [comment]
Hi @SimonWesterlindVPD - that's a good point.  It should be tried with the other detectors as well. It would be great if you want to try it out and report the results 😃 

Personally I don't know that it will have much effect. This was put in to catch some spatial anomalies specifically missed by the core detector, and had only a small impact (the HTM still caught a lot of spatial anomalies). KNN-CAD and CAD-OSE were third party competition entries, and were added to NAB as-is, so not sure I want to touch those. Those authors presumably tried a bunch of such techniques already.
