### ISSUE TITLE
miscalculation of scores 

### ISSUE THREAD

**Issue by alaineiturria** [numenta/NAB#321]
To calculate the size of the windows, is it calculated considering the number of anomalies per data set present in the combined_labels.json file or those present in the combined_windows.json file? 

I have been able to observe that the scores in the results/null/null_standard_scores.csv file are obtained using the combined_windows.json file, however, it seems to me that the anomalies present in combined_labels.json file are used to calculate the rest of the scores.

**Comment by subutai** [comment]
The window size calculation is described in the paper: "we define anomaly window length to be 10% the length of a data file, divided by the number of anomalies in the given file."

For each data file, the number of anomalies and their centers are given in the combined_labels.json file. The resulting windows are then put in combined_windows.json. This whole process is run by the [combine_labels.py](https://github.com/numenta/NAB/blob/master/scripts/combine_labels.py) script.

Some more details are in the [NAB whitepaper](https://github.com/numenta/NAB/wiki#nab-whitepaper)

For questions like these it might be better to ask on the [HTM NAB Forum](https://discourse.numenta.org/c/nupic/nab) unless you see a specific bug we need to address.

Hope this helps!
