### ISSUE TITLE
Calculation of TP and FN

### ISSUE THREAD

**Issue by avm-ru-cs** [numenta/NAB#326]
I am exploring Option 2 of the NAB Entry Points (NAB source code obtained today via `git clone https://github.com/numenta/NAB.git`. While doing so, I got confused about how optimizer selects the best anomaly threshold. An example is given below.

Assume that `t_i` and `t_{i+1}` are within an anomaly window. The resulting file will have a number of observations, e.g.:

|timestamp | value | anomaly_score|
| --- | --- | --- |
| ... | ... | ... |
|t_i | 5 | 0.875 |
|t_{i+1} | 10 | 0.901 |
| ... | ... | ... |

The optimizer of threshold selection correctly sets the threshold at 0.8749 and marks both observations as true positives in `*_scores.csv` files.

Let us swap the observations, yielding

|timestamp | value | anomaly_score|
| --- | --- | --- |
| ... | ... | ... |
|t_i | 5 | 0.901 |
|t_{i+1} | 10 | 0.875 |
| ... | ... | ... |

In this case, optimizer increases the threshold to 0.899, marking observation at `t_{i+1}` as a false negative in `*_scores.csv` files.

Naively, the order of observations should not matter, i.e., the threshold for both cases should be selected as 0.8749. In turn, we should get two true positive observations in both cases.

To reproduce this issue, please take a look at [sample_files.zip](https://github.com/numenta/NAB/files/2706401/sample_files.zip) archive containing two sample result files. The only difference between the files is on lines  `2973` and `2974`:

```
$ diff alpha_ec2_cpu_utilization_5f5533.csv.v1 alpha_ec2_cpu_utilization_5f5533.csv.v2
2973,2974c2973,2974
< 2014-02-24 22:02,37.816,0.8786448134856168
< 2014-02-24 22:07,40.446,0.91399619188219234
---
> 2014-02-24 22:02,37.816,0.91399619188219234
> 2014-02-24 22:07,40.446,0.8786448134856168
```

And to get the count of TP and FN we can run something like

```bash
python scripts/create_new_detector.py --detector alpha

cp alpha_ec2_cpu_utilization_5f5533.csv.v1 ./results/alpha/realAWSCloudwatch/alpha_ec2_cpu_utilization_5f5533.csv
python run.py -d alpha --optimize --score --normalize
#The script says:
#Optimizer found a max score of -0.358495402625 with anomaly threshold 0.874998474121.
# In all of the _score.csv files I see 2 TP and 400 FN observations

cp alpha_ec2_cpu_utilization_5f5533.csv.v2 ./results/alpha/realAWSCloudwatch/alpha_ec2_cpu_utilization_5f5533.csv
python run.py -d alpha --optimize --score --normalize
#Optimizer found a max score of -0.358495402625 with anomaly threshold 0.899609375.
#In all of the _score.csv files I see 1 TP and 401 FN observations
```

**Comment by rhyolight** [comment]
Thanks for creating this. I have a couple of NAB PRs to work on this week, so I'll look into this then.

**Comment by avm-ru-cs** [comment]
Thank you, @rhyolight! If you need any additional info -- please let me know.

**Comment by avm-ru-cs** [comment]
Hi @subutai,
Could you please tell me, was the issue fixed? I do not see any code commits associated with it.
