### ISSUE TITLE
Disable skyline detector by default

### ISSUE THREAD

**Issue by earthgecko** [numenta/NAB#333]
Disabling the skyline detector by default going forward will decrease the default run.py run time significantly.

The intention here is to not deprecate the skyline detector but make it so that it must be declared in an argument to be run.  This way it can still be used in > v1.0 scoring, but the general community is not subjected to the cost on the time and computation overhead of scoring with this specific detector.  Which has proved the longest running of all the detectors.  As discussed in https://github.com/numenta/NAB/pull/330/

This author shall endeavour to submit scores for the skyline detector on any future versions.

**Comment by rhyolight** [comment]
Good initiative! I'm not sure when we will be ready to push a version but this will be included in it. Thanks @earthgecko.

**Comment by breznak** [comment]
@earthgecko this can be closed as fixed (?)

**Comment by earthgecko** [comment]
Hi @breznak yes #335 closes this.  Done.
