### ISSUE TITLE
Where are the labels in the CSV files?

### ISSUE THREAD

**Issue by kdlin** [numenta/NAB#362]
Can someone please explain how I can get the labels? The data are stored as CSV files with timestamps and values only.  Aren't they supposed to be labeled data? Thanks.

**Comment by subutai** [comment]
Please see the directory named `labels` and the [NAB whitepaper](https://drive.google.com/file/d/0B1_XUjaAXeV3dW1kX1B3VkYwOFE/view?usp=sharing) (referenced from the [wiki](https://github.com/numenta/NAB/wiki))
