### ISSUE TITLE
Error while running python run.py -d expose --detect --optimize --score --normalize

### ISSUE THREAD

**Issue by Tann10** [numenta/NAB#370]
I am getting a value error when I am trying to run the package. Error is "ValueError: anomalyScore must be a number between 0 and 1. Please verify if 'ExposeDetector.handleRecord' method is returning a value between 0 and 1" I am also attaching a screenshot.
![error](https://user-images.githubusercontent.com/54607338/88865301-d0542180-d207-11ea-9baa-4cd692be6e3a.PNG)

Any help is appreciated! Thanks

**Comment by subutai** [comment]
Thanks, this is due to a recent change in error checking. We're putting in a fix:

https://github.com/numenta/NAB/pull/371

**Comment by Tann10** [comment]
@subutai Great! Thank you for letting me know. I see the PR is already merged. I will pull recent changes.
