### ISSUE TITLE
Scoring Issue with ambient_temperature_system_failure.csv

### ISSUE THREAD

**Issue by g-luo** [numenta/NAB#378]
Hello! I am trying to run the scoring algorithm on my results but I keep receiving the error "AssertionError: timestamps and anomalyScores should not be different lengths!" -- it seems like the start and end timestamp are the same for my timestamps and anomalyScores lists, but some of the GT labels (timestamps) are missing.

Do you have any insight for why scoring is failing for me? Thanks! Also attached is my results file.

[tsad_ambient_temperature_system_failure.csv](https://github.com/numenta/NAB/files/6804255/tsad_ambient_temperature_system_failure.csv)

**Comment by g-luo** [comment]
bump! @lscheinkman

**Comment by lscheinkman** [comment]
It looks like your file is missing **anomay_score** values for the following rows: 

- 578-611  
- 1308-1354
- 1629-1787
- 2053-2147
- 2397-2466
- 5788-5816
- 6171-6172
- 6317-6330
- 6562-6736

**Comment by g-luo** [comment]
Thanks! That was indeed the issue -- my algorithm was missing rows for certain timestamps.
