### ISSUE TITLE
results problem

### ISSUE THREAD

**Issue by ir1979** [numenta/NAB#379]
In the results files we have:   FP+FN+TP+TN != TotalNumberOfRecords. Why?

**Comment by lscheinkman** [comment]
During the detection phase there is **probationary period** where no scoring is done. This probationary period is set at _750_ points for data files larger than _5000_ points or _15%_ of the total records for files shorter than _5000_. 

**FP+FN+TP+TN** = Total number of scored data points (excluding probationary period) 
**Total_Count** = Total number of data points in the dataset (including probationary period)

Please refer to [NAB Whitepaper, Section 3.1](https://drive.google.com/file/d/0B1_XUjaAXeV3dW1kX1B3VkYwOFE/view?resourcekey=0-swTidTTt83zFVZTGvoYxXgl) for more details.

**Comment by ir1979** [comment]
Thanks
