### ISSUE TITLE
Run NumentaHTM on specific data 

### ISSUE THREAD

**Issue by jorgegarcia197** [numenta/NAB#390]
Hi, I am really interesting on implementing an Anomaly Detection application for streaming data, and I came across this repository. 
Having said this, I would like to dig further and run de NumentaHTM detector on just a single dataset that resembles the data I have collected for my own project. For this specific case I would like to run the HTM detector on the AWSCloudWatch dataset. 

And just wondering if that detector is able to run on a python3 environment. 

Thanks in advance!

**Comment by markNZed** [comment]
I believe the NumentaHTM detector uses Python2. The community version might be a better bet for Python 3 https://github.com/htm-community/htm.core You could also run the detector with NumentaHTM Python 2 and NAB in Python 3 - I think that is how it is intended to work at the moment.
