### ISSUE TITLE
What is the meaning of the labels folder？

### ISSUE THREAD

**Issue by BluthLeee** [numenta/NAB#392]
I did not find the description of the labels folder in the readme file. I don't understand the meaning and difference of the multiple files contained in the folder. Take the Twitter_volume_AAPL.csv file in REALTWEETS as an example. The data marked by AL_lables_v1.0.json, CB_lables_v1.0.json, and SA_lables_v1.0.json are not the same. Which one is the correct manual marking?
Looking forward to your reply~

**Comment by subutai** [comment]
Please see the [NAB whitepaper](https://github.com/numenta/NAB/wiki#nab-whitepaper) which contains all the details about the files, labeling process, etc.  NAB combines multiple labels from humans to correct for manual errors. Those files are from different human labelers.
