### ISSUE TITLE
Add new CPU load datafile

### ISSUE THREAD

**Issue by subutai** [numenta/NAB#42]
We received a new data file with a real anomaly. Get the file "9f78a90223174506a8ad262b0.csv" from Subutai and add to dataset.

**Comment by BoltzmannBrain** [comment]
@subutai could you please send me this data?

*Note: this is a subtask of #132*

**Comment by subutai** [comment]
Looks like we missed this. Maybe consider this for v2.0?

**Comment by BoltzmannBrain** [comment]
Sure, but do you know what data file this is referring to?

**Comment by subutai** [comment]
Yes, I have the file. It is customer data.
