### ISSUE TITLE
Use simplejson throughout

### ISSUE THREAD

**Issue by BoltzmannBrain** [numenta/NAB#51]
Should be using simplejson rather than json for faster loading/dumping. Not significant now with such small json files, but can only help when they grow -- more user profiles.

**Comment by subutai** [comment]
I think we just switched from simplejson back to json didn't we? simplejson requires an external library. Not sure there's any need to optimize our json usage.

**Comment by BoltzmannBrain** [comment]
Oh I'm sorry I thought we wanted to use the try/except for simplejson. And simplejson is in the requirements.txt. Should I change nab back to using json?

**Comment by subutai** [comment]
I actually don't remember now which way it went. I remember us trying to switch from one to the other and it just seems like a waste of time.
