### ISSUE TITLE
run.py doesn't cover all detectors

### ISSUE THREAD

**Issue by BoltzmannBrain** [numenta/NAB#63]
Running run.py only uses the Numenta detector, but should include the Skyline and random detectors too.

**Comment by subutai** [comment]
Isn't it just a command line option to run the others? Or do you mean what run.py does by default?

**Comment by BoltzmannBrain** [comment]
It should by default, as specified in the readme.

**Comment by subutai** [comment]
Is this issue complete? It's still open.
