### ISSUE TITLE
Better command line UX

### ISSUE THREAD

**Issue by BoltzmannBrain** [numenta/NAB#68]
Users should be able to easily set parameters, particularly which individual detectors and profiles to run because they take a while. They can do this manually in the code, but it would be much better from command line (with supporting instructions and examples in the readme).

**Comment by subutai** [comment]
How is this different from existing options such as `profilesFile`?

**Comment by BoltzmannBrain** [comment]
I was trying to think of how NAB can be simpler (more accessible) to new users. You're right, I was not aware the user could change the arguments from the command line. However it's not explicitly stated anywhere how to do this. Do you think we need to explain these options? If so, should the details be in the readme or the writeup?

**Comment by subutai** [comment]
If you do run.py --help it provides a nice description of all the options. This is similar to most Unix commands. We can put that note in the README.
