### ISSUE TITLE
Data analysis tools

### ISSUE THREAD

**Issue by BoltzmannBrain** [numenta/NAB#76]
Plotting the anomaly detection results is helpful for debugging, and could also be included in a "NAB Data Analysis" section of the repo, along with the data visualizer. The visualizer does give results plots, but they're not very intuitive (confusing) and not too useful (don't show the ground truth windows).

**Comment by subutai** [comment]
@BoltzmannBrain The visualizer can plot results.

**Comment by BoltzmannBrain** [comment]
@subutai thanks, I did not think of that. But now that I'm trying it I see it's not working properly; I don't see any results plots. Will you try the visualizer and see if you have the same issue?

**Comment by BoltzmannBrain** [comment]
We may wish to use plotly for all visualizations; could better enable other users to plot NAB data and results, and in general offers some cool features.

**Comment by BoltzmannBrain** [comment]
Moving up to P2 b/c better results analyses/visualizations was requested by Jeff.

**Comment by BoltzmannBrain** [comment]
#180 updated the plotting script with explanation and examples for plotting data and results.
