### ISSUE TITLE
Normalize scores

### ISSUE THREAD

**Issue by BoltzmannBrain** [numenta/NAB#83]
Scale/normalize the final scores such that adding files to the corpus will not (necessarily) decrease the scores, i.e. appear worse. E.g. the current best DUT may have a NAB score of -7, and then with a new datafile added to the corpus, score a -8, and appear to be performing worse.

We may also want to modify the scoring profiles such that a perfect TP detection actually yields a 1; currently it is 0.98661.

**Comment by subutai** [comment]
This is a good idea but I don't think it's necessary for the Private Beta milestone.

**Comment by BoltzmannBrain** [comment]
OK.
What do you think about the 2nd part of the issue -- scaling the TP scores? Two possible alternatives for doing this are to reward a TP with a score of 1 if the detection is at either (i) the very front of the window, or (ii) at the middle of the window; the middle of the window is the timestamp of the ground truth TP. For (ii), a detection preceding the middle of the window would yield a score >1.

**Comment by subutai** [comment]
I am fine with scaling the TP scores. Not sure we should make the max score > 1 - that is basically the same problem as having the max score be < 1. Scaling it to 1 seems simplest and cleanest to explain.

**Comment by BoltzmannBrain** [comment]
PR#88 scales the scores, and now I'd like to normalize them. I intend to normalize for the the number of data points, rather than the number of data files, because the lengths of data files vary. @subutai do you think the normalization should be reflected throughout NAB scoring, or separately for scoreboard purposes only?
